### ISSUE TITLE
Avancement sur les exercices de TPs

### ISSUE THREAD

**Issue by LBF38** [LBF38/projet-java-enstab#7]
# TPs Java
A ajouter au repo : 
- le sujet des TPs Java
- Une documentation (à voir en fonction du temps)

# Liste des exercices à faire 
basé sur le sujet des TPs

## Notions de base du langage et fonctions anonymes

- [x] No Pain, No Gain
- [x] Un peu de récursivité
- [x] Méthodes de tris #2 
   - [x] Tri bulle (bubbleSort)
   - [x] Tri par insertion (insertionSort)
- [x] Température par villes #3 

## Notions de base de la programmation orientée objet et les génériques de Java

- [x] Dépôt de voitures d'occasion (@The Australian National University) #6 
- [x] Compte bancaire #25 
- [x] #9
- [x] #10
- [x] #11

## Notions avancées de la POO

- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16

## Gestion d’erreurs

- [x] Exceptions (© Dr Robert Harle) #4 
- [x] #17
- [x] #18
- [x] Compte bancaire JUnit (continuation de la partie précédente) #40 
- [x] #19

## JavaFX

- [ ] #20
- [ ] #21
- [ ] #22
- [ ] #23
- [ ] #24

**Comment by LBF38** [comment]
Need to finish JavaFX workshops if time after implementing the Duel Invaders project
